"""
load_to_db.py
─────────────
Reads the three parsed CSVs and loads them into PostgreSQL.
Creates all tables first, then inserts data.

Usage (from backend/ folder):
    python scripts/load_to_db.py

Requirements:
  - PostgreSQL running locally
  - .env file with correct DATABASE_URL
  - CSVs already generated by parse_cricsheet.py
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pandas as pd
from pathlib import Path
from sqlalchemy import text
from database import engine, Base, SessionLocal
from models.db_models import Venue, Match, Innings, Delivery, Player

PARSED_DIR = Path(__file__).parent.parent / "data" / "parsed"


def create_tables():
    """Drop and recreate all tables. WARNING: deletes existing data."""
    print("🗃️  Creating tables...")
    # Only create real tables — skip virtual view models
    from sqlalchemy import inspect
    Base.metadata.create_all(bind=engine, tables=[
        Venue.__table__,
        Player.__table__,
        Match.__table__,
        Innings.__table__,
        Delivery.__table__,
    ])
    print("   Tables created.")


def load_venues(matches_df: pd.DataFrame, db) -> dict:
    """Insert unique venues, return name→id map."""
    print("📍 Loading venues...")
    venues = matches_df[["venue", "city"]].drop_duplicates("venue")
    venue_map = {}

    for _, row in venues.iterrows():
        name = str(row["venue"]) if pd.notna(row["venue"]) else "Unknown"
        city = str(row["city"]) if pd.notna(row.get("city")) else None

        # Infer country from venue name (basic heuristic for SL project)
        country = infer_country(name)

        v = db.query(Venue).filter_by(name=name).first()
        if not v:
            v = Venue(name=name, city=city, country=country)
            db.add(v)
            db.flush()
        venue_map[name] = v.id

    db.commit()
    print(f"   Loaded {len(venue_map)} venues.")
    return venue_map


def infer_country(venue_name: str) -> str:
    """Basic country inference from known venue keywords."""
    name = venue_name.lower()
    mapping = {
        "colombo": "Sri Lanka", "kandy": "Sri Lanka", "galle": "Sri Lanka",
        "pallekele": "Sri Lanka", "dambulla": "Sri Lanka", "hambantota": "Sri Lanka",
        "sydney": "Australia", "melbourne": "Australia", "brisbane": "Australia",
        "perth": "Australia", "adelaide": "Australia", "hobart": "Australia",
        "lord": "England", "oval": "England", "edgbaston": "England",
        "headingley": "England", "trent bridge": "England", "manchester": "England",
        "eden gardens": "India", "wankhede": "India", "chinnaswamy": "India",
        "feroz shah": "India", "rajiv gandhi": "India",
        "auckland": "New Zealand", "wellington": "New Zealand", "christchurch": "New Zealand",
        "cape town": "South Africa", "johannesburg": "South Africa", "centurion": "South Africa",
        "dubai": "UAE", "abu dhabi": "UAE", "sharjah": "UAE",
        "lahore": "Pakistan", "karachi": "Pakistan", "rawalpindi": "Pakistan",
        "mirpur": "Bangladesh", "chittagong": "Bangladesh", "dhaka": "Bangladesh",
    }
    for keyword, country in mapping.items():
        if keyword in name:
            return country
    return "Unknown"


def load_players(deliveries_df: pd.DataFrame, db) -> None:
    """Insert unique player names."""
    print("👤 Loading players...")
    batters = set(deliveries_df["batter"].dropna().unique())
    bowlers = set(deliveries_df["bowler"].dropna().unique())
    all_players = batters | bowlers

    existing = {p.name for p in db.query(Player.name).all()}
    new_players = [Player(name=name) for name in all_players if name not in existing]
    db.bulk_save_objects(new_players)
    db.commit()
    print(f"   Loaded {len(new_players)} players.")


def load_matches(matches_df: pd.DataFrame, venue_map: dict, db) -> dict:
    """Insert matches, return cricsheet_id→match.id map."""
    print("🏏 Loading matches...")
    match_map = {}

    for _, row in matches_df.iterrows():
        cid = str(row["cricsheet_id"])
        venue_name = str(row["venue"]) if pd.notna(row["venue"]) else "Unknown"
        venue_id = venue_map.get(venue_name)

        # Parse date safely
        match_date = None
        if pd.notna(row.get("date")):
            try:
                match_date = pd.to_datetime(row["date"]).date()
            except Exception:
                pass

        m = Match(
            cricsheet_id=cid,
            date=match_date,
            venue_id=venue_id,
            team1=str(row["team1"]) if pd.notna(row.get("team1")) else None,
            team2=str(row["team2"]) if pd.notna(row.get("team2")) else None,
            toss_winner=str(row["toss_winner"]) if pd.notna(row.get("toss_winner")) else None,
            toss_decision=str(row["toss_decision"]) if pd.notna(row.get("toss_decision")) else None,
            winner=str(row["winner"]) if pd.notna(row.get("winner")) else None,
            win_by_runs=int(row["win_by_runs"]) if pd.notna(row.get("win_by_runs")) else None,
            win_by_wickets=int(row["win_by_wickets"]) if pd.notna(row.get("win_by_wickets")) else None,
            no_result=bool(row.get("no_result", False)),
            season=str(row["season"]) if pd.notna(row.get("season")) else None,
        )
        db.add(m)
        db.flush()
        match_map[cid] = m.id

    db.commit()
    print(f"   Loaded {len(match_map)} matches.")
    return match_map


def load_innings(innings_df: pd.DataFrame, match_map: dict, db) -> dict:
    """Insert innings, return (cricsheet_id, innings_number)→innings.id map."""
    print("📊 Loading innings...")
    innings_map = {}

    for _, row in innings_df.iterrows():
        cid = str(row["match_cricsheet_id"])
        match_id = match_map.get(cid)
        if not match_id:
            continue

        inn_num = int(row["innings_number"])
        inn = Innings(
            match_id=match_id,
            innings_number=inn_num,
            batting_team=str(row["batting_team"]),
            bowling_team=str(row["bowling_team"]),
            total_runs=int(row["total_runs"]) if pd.notna(row["total_runs"]) else 0,
            total_wickets=int(row["total_wickets"]) if pd.notna(row["total_wickets"]) else 0,
            total_overs=float(row["total_overs"]) if pd.notna(row["total_overs"]) else 0.0,
        )
        db.add(inn)
        db.flush()
        innings_map[(cid, inn_num)] = inn.id

    db.commit()
    print(f"   Loaded {len(innings_map)} innings.")
    return innings_map


def load_deliveries(deliveries_df: pd.DataFrame, match_map: dict, innings_map: dict, db) -> None:
    """Bulk insert all deliveries — the biggest table."""
    print("⚾ Loading deliveries (this may take a minute)...")
    total = len(deliveries_df)
    batch_size = 5000
    loaded = 0

    for start in range(0, total, batch_size):
        batch = deliveries_df.iloc[start:start + batch_size]
        objects = []

        for _, row in batch.iterrows():
            cid = str(row["match_cricsheet_id"])
            inn_num = int(row["innings_number"])
            match_id = match_map.get(cid)
            innings_id = innings_map.get((cid, inn_num))

            if not match_id or not innings_id:
                continue

            objects.append(Delivery(
                innings_id=innings_id,
                match_id=match_id,
                over_number=int(row["over_number"]),
                ball_number=int(row["ball_number"]),
                phase=str(row["phase"]),
                batter=str(row["batter"]) if pd.notna(row["batter"]) else "",
                bowler=str(row["bowler"]) if pd.notna(row["bowler"]) else "",
                non_striker=str(row["non_striker"]) if pd.notna(row["non_striker"]) else "",
                runs_batter=int(row["runs_batter"]),
                runs_extras=int(row["runs_extras"]),
                runs_total=int(row["runs_total"]),
                is_wide=bool(row["is_wide"]),
                is_noball=bool(row["is_noball"]),
                is_bye=bool(row["is_bye"]),
                is_legbye=bool(row["is_legbye"]),
                is_wicket=bool(row["is_wicket"]),
                wicket_kind=str(row["wicket_kind"]) if pd.notna(row.get("wicket_kind")) else None,
                player_out=str(row["player_out"]) if pd.notna(row.get("player_out")) else None,
                is_boundary_four=bool(row["is_boundary_four"]),
                is_boundary_six=bool(row["is_boundary_six"]),
            ))

        db.bulk_save_objects(objects)
        db.commit()
        loaded += len(objects)
        print(f"   {loaded:,} / {total:,} deliveries loaded...")

    print(f"   ✅ All deliveries loaded.")


def main():
    # Check CSVs exist
    required = ["matches.csv", "innings.csv", "deliveries.csv"]
    for f in required:
        if not (PARSED_DIR / f).exists():
            print(f"❌ Missing: {PARSED_DIR / f}")
            print("   Run parse_cricsheet.py first!")
            return

    matches_df = pd.read_csv(PARSED_DIR / "matches.csv")
    innings_df = pd.read_csv(PARSED_DIR / "innings.csv")
    deliveries_df = pd.read_csv(PARSED_DIR / "deliveries.csv")

    print(f"📋 Loaded CSVs:")
    print(f"   Matches:    {len(matches_df):,}")
    print(f"   Innings:    {len(innings_df):,}")
    print(f"   Deliveries: {len(deliveries_df):,}")
    print()

    create_tables()

    db = SessionLocal()
    try:
        venue_map = load_venues(matches_df, db)
        load_players(deliveries_df, db)
        match_map = load_matches(matches_df, venue_map, db)
        innings_map = load_innings(innings_df, match_map, db)
        load_deliveries(deliveries_df, match_map, innings_map, db)
    finally:
        db.close()

    print("\n🎉 Database loading complete!")
    print("   You can now start the FastAPI server.")


if __name__ == "__main__":
    main()
